### ISSUE TITLE
Add scope to submodules

### ISSUE THREAD

**Issue by paluh** [gaku-sei/purescript-node-jwt#9]
Thanks for providing these bindings!

I see that you use global scope for some of the library modules like _Options.purs_ or _Types.purs_. Shouldn't they be scoped by `Node.Jwt` or something similar?

**Comment by gaku-sei** [comment]
You're absolutely right, my bad, I'm too used to work on applications rather libraries I guess 😓 

I just merged https://github.com/gaku-sei/purescript-node-jwt/pull/10 which should solve the issue. Please feel free to reopen if that's not the case.

(Also, I might release 0.2.0 soon, including the above changes)
